name: Testing the LTZF Backend

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    environment: docker-deploy
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Log into docker"
        uses: docker/login-action@v3
        with:
          username: crystalkey
          password: ${{ secrets.DH_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: "Build & Push"
        id: push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.deploy
          push: true
          tags: crystalkey/ltzf-backend:0.2.5